### ISSUE TITLE
Minor issues following the wiki 01 First boot

### ISSUE THREAD

**Issue by cprima** [mck-sbs/gentoo-rpi-64-bit#3]
## ERROR
edit /etc/locale.gen with nan and set locales
> Depending in the skilllevel of your students they might not recognize `nano`. Maybe also markup inline with a single backtick to show that it is a command?

## FATAL
config_etho="192.168.0.11/24"
routes_eth0="default via 192.168.0.1"
>eth o

**Comment by mck-sbs** [comment]
Fixed that. Thank you.
