### ISSUE TITLE
Minor issues following the wiki 04 wifi

### ISSUE THREAD

**Issue by cprima** [mck-sbs/gentoo-rpi-64-bit#5]
Unless I cloned the kernel sources the emerge of wpa_supplicant would complain about missing /usr/src/linux files.
I am not sure if that affects the result, as I interrupted the emerge command and got the sources right away.

This is _after_ getting the kernel sources:

```bash
>>> Running pre-merge checks for net-wireless/wpa_supplicant-2.10-r1
 * Determining the location of the kernel source code
 * Found kernel source directory:
 *     /usr/src/linux
 ```

**Comment by mck-sbs** [comment]
You don’t need to install the kernel sources, because you cross-compiled the sources on the host machine. This warning is ok. You can emerge wpa_supplicant without installing the kernel sources.
